// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Sorrowful-free/z-core-frontier-rooms/internal/port/reservation (interfaces: Reservation)
//
// Generated by this command:
//
//	mockgen -typed -destination=mock_reservation.go -package=mocks github.com/Sorrowful-free/z-core-frontier-rooms/internal/port/reservation Reservation
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/Sorrowful-free/z-core-frontier-rooms/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockReservation is a mock of Reservation interface.
type MockReservation struct {
	ctrl     *gomock.Controller
	recorder *MockReservationMockRecorder
	isgomock struct{}
}

// MockReservationMockRecorder is the mock recorder for MockReservation.
type MockReservationMockRecorder struct {
	mock *MockReservation
}

// NewMockReservation creates a new mock instance.
func NewMockReservation(ctrl *gomock.Controller) *MockReservation {
	mock := &MockReservation{ctrl: ctrl}
	mock.recorder = &MockReservationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReservation) EXPECT() *MockReservationMockRecorder {
	return m.recorder
}

// Admit mocks base method.
func (m *MockReservation) Admit(ctx context.Context, roomID domain.RoomID, peerID domain.PeerID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Admit", ctx, roomID, peerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Admit indicates an expected call of Admit.
func (mr *MockReservationMockRecorder) Admit(ctx, roomID, peerID any) *MockReservationAdmitCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Admit", reflect.TypeOf((*MockReservation)(nil).Admit), ctx, roomID, peerID)
	return &MockReservationAdmitCall{Call: call}
}

// MockReservationAdmitCall wrap *gomock.Call
type MockReservationAdmitCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReservationAdmitCall) Return(arg0 error) *MockReservationAdmitCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReservationAdmitCall) Do(f func(context.Context, domain.RoomID, domain.PeerID) error) *MockReservationAdmitCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReservationAdmitCall) DoAndReturn(f func(context.Context, domain.RoomID, domain.PeerID) error) *MockReservationAdmitCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListAdmittedPeers mocks base method.
func (m *MockReservation) ListAdmittedPeers(ctx context.Context, roomID domain.RoomID) ([]domain.AdmittedSlot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAdmittedPeers", ctx, roomID)
	ret0, _ := ret[0].([]domain.AdmittedSlot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAdmittedPeers indicates an expected call of ListAdmittedPeers.
func (mr *MockReservationMockRecorder) ListAdmittedPeers(ctx, roomID any) *MockReservationListAdmittedPeersCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAdmittedPeers", reflect.TypeOf((*MockReservation)(nil).ListAdmittedPeers), ctx, roomID)
	return &MockReservationListAdmittedPeersCall{Call: call}
}

// MockReservationListAdmittedPeersCall wrap *gomock.Call
type MockReservationListAdmittedPeersCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReservationListAdmittedPeersCall) Return(arg0 []domain.AdmittedSlot, arg1 error) *MockReservationListAdmittedPeersCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReservationListAdmittedPeersCall) Do(f func(context.Context, domain.RoomID) ([]domain.AdmittedSlot, error)) *MockReservationListAdmittedPeersCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReservationListAdmittedPeersCall) DoAndReturn(f func(context.Context, domain.RoomID) ([]domain.AdmittedSlot, error)) *MockReservationListAdmittedPeersCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RegisterRoom mocks base method.
func (m *MockReservation) RegisterRoom(ctx context.Context, roomID domain.RoomID, capacity int, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterRoom", ctx, roomID, capacity, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterRoom indicates an expected call of RegisterRoom.
func (mr *MockReservationMockRecorder) RegisterRoom(ctx, roomID, capacity, password any) *MockReservationRegisterRoomCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterRoom", reflect.TypeOf((*MockReservation)(nil).RegisterRoom), ctx, roomID, capacity, password)
	return &MockReservationRegisterRoomCall{Call: call}
}

// MockReservationRegisterRoomCall wrap *gomock.Call
type MockReservationRegisterRoomCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReservationRegisterRoomCall) Return(arg0 error) *MockReservationRegisterRoomCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReservationRegisterRoomCall) Do(f func(context.Context, domain.RoomID, int, string) error) *MockReservationRegisterRoomCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReservationRegisterRoomCall) DoAndReturn(f func(context.Context, domain.RoomID, int, string) error) *MockReservationRegisterRoomCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Reserve mocks base method.
func (m *MockReservation) Reserve(ctx context.Context, roomID domain.RoomID, peerID domain.PeerID, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reserve", ctx, roomID, peerID, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reserve indicates an expected call of Reserve.
func (mr *MockReservationMockRecorder) Reserve(ctx, roomID, peerID, expiresAt any) *MockReservationReserveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reserve", reflect.TypeOf((*MockReservation)(nil).Reserve), ctx, roomID, peerID, expiresAt)
	return &MockReservationReserveCall{Call: call}
}

// MockReservationReserveCall wrap *gomock.Call
type MockReservationReserveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReservationReserveCall) Return(arg0 error) *MockReservationReserveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReservationReserveCall) Do(f func(context.Context, domain.RoomID, domain.PeerID, time.Time) error) *MockReservationReserveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReservationReserveCall) DoAndReturn(f func(context.Context, domain.RoomID, domain.PeerID, time.Time) error) *MockReservationReserveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Revoke mocks base method.
func (m *MockReservation) Revoke(ctx context.Context, roomID domain.RoomID, peerID domain.PeerID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, roomID, peerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockReservationMockRecorder) Revoke(ctx, roomID, peerID any) *MockReservationRevokeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockReservation)(nil).Revoke), ctx, roomID, peerID)
	return &MockReservationRevokeCall{Call: call}
}

// MockReservationRevokeCall wrap *gomock.Call
type MockReservationRevokeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReservationRevokeCall) Return(arg0 error) *MockReservationRevokeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReservationRevokeCall) Do(f func(context.Context, domain.RoomID, domain.PeerID) error) *MockReservationRevokeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReservationRevokeCall) DoAndReturn(f func(context.Context, domain.RoomID, domain.PeerID) error) *MockReservationRevokeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// State mocks base method.
func (m *MockReservation) State(ctx context.Context, roomID domain.RoomID, peerID domain.PeerID) (domain.ReservationSlot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "State", ctx, roomID, peerID)
	ret0, _ := ret[0].(domain.ReservationSlot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// State indicates an expected call of State.
func (mr *MockReservationMockRecorder) State(ctx, roomID, peerID any) *MockReservationStateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "State", reflect.TypeOf((*MockReservation)(nil).State), ctx, roomID, peerID)
	return &MockReservationStateCall{Call: call}
}

// MockReservationStateCall wrap *gomock.Call
type MockReservationStateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReservationStateCall) Return(arg0 domain.ReservationSlot, arg1 error) *MockReservationStateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReservationStateCall) Do(f func(context.Context, domain.RoomID, domain.PeerID) (domain.ReservationSlot, error)) *MockReservationStateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReservationStateCall) DoAndReturn(f func(context.Context, domain.RoomID, domain.PeerID) (domain.ReservationSlot, error)) *MockReservationStateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UnregisterRoom mocks base method.
func (m *MockReservation) UnregisterRoom(ctx context.Context, roomID domain.RoomID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnregisterRoom", ctx, roomID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnregisterRoom indicates an expected call of UnregisterRoom.
func (mr *MockReservationMockRecorder) UnregisterRoom(ctx, roomID any) *MockReservationUnregisterRoomCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnregisterRoom", reflect.TypeOf((*MockReservation)(nil).UnregisterRoom), ctx, roomID)
	return &MockReservationUnregisterRoomCall{Call: call}
}

// MockReservationUnregisterRoomCall wrap *gomock.Call
type MockReservationUnregisterRoomCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReservationUnregisterRoomCall) Return(arg0 error) *MockReservationUnregisterRoomCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReservationUnregisterRoomCall) Do(f func(context.Context, domain.RoomID) error) *MockReservationUnregisterRoomCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReservationUnregisterRoomCall) DoAndReturn(f func(context.Context, domain.RoomID) error) *MockReservationUnregisterRoomCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// VerifyRoomPassword mocks base method.
func (m *MockReservation) VerifyRoomPassword(ctx context.Context, roomID domain.RoomID, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyRoomPassword", ctx, roomID, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyRoomPassword indicates an expected call of VerifyRoomPassword.
func (mr *MockReservationMockRecorder) VerifyRoomPassword(ctx, roomID, password any) *MockReservationVerifyRoomPasswordCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyRoomPassword", reflect.TypeOf((*MockReservation)(nil).VerifyRoomPassword), ctx, roomID, password)
	return &MockReservationVerifyRoomPasswordCall{Call: call}
}

// MockReservationVerifyRoomPasswordCall wrap *gomock.Call
type MockReservationVerifyRoomPasswordCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReservationVerifyRoomPasswordCall) Return(arg0 error) *MockReservationVerifyRoomPasswordCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReservationVerifyRoomPasswordCall) Do(f func(context.Context, domain.RoomID, string) error) *MockReservationVerifyRoomPasswordCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReservationVerifyRoomPasswordCall) DoAndReturn(f func(context.Context, domain.RoomID, string) error) *MockReservationVerifyRoomPasswordCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
