// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Sorrowful-free/z-core-frontier-rooms/internal/port/admission (interfaces: Admission)
//
// Generated by this command:
//
//	mockgen -typed -destination=mock_admission.go -package=mocks github.com/Sorrowful-free/z-core-frontier-rooms/internal/port/admission Admission
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Sorrowful-free/z-core-frontier-rooms/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAdmission is a mock of Admission interface.
type MockAdmission struct {
	ctrl     *gomock.Controller
	recorder *MockAdmissionMockRecorder
	isgomock struct{}
}

// MockAdmissionMockRecorder is the mock recorder for MockAdmission.
type MockAdmissionMockRecorder struct {
	mock *MockAdmission
}

// NewMockAdmission creates a new mock instance.
func NewMockAdmission(ctrl *gomock.Controller) *MockAdmission {
	mock := &MockAdmission{ctrl: ctrl}
	mock.recorder = &MockAdmissionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdmission) EXPECT() *MockAdmissionMockRecorder {
	return m.recorder
}

// Issue mocks base method.
func (m *MockAdmission) Issue(ctx context.Context, roomID domain.RoomID, peerID domain.PeerID, password string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Issue", ctx, roomID, peerID, password)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Issue indicates an expected call of Issue.
func (mr *MockAdmissionMockRecorder) Issue(ctx, roomID, peerID, password any) *MockAdmissionIssueCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Issue", reflect.TypeOf((*MockAdmission)(nil).Issue), ctx, roomID, peerID, password)
	return &MockAdmissionIssueCall{Call: call}
}

// MockAdmissionIssueCall wrap *gomock.Call
type MockAdmissionIssueCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdmissionIssueCall) Return(arg0 []byte, arg1 error) *MockAdmissionIssueCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdmissionIssueCall) Do(f func(context.Context, domain.RoomID, domain.PeerID, string) ([]byte, error)) *MockAdmissionIssueCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdmissionIssueCall) DoAndReturn(f func(context.Context, domain.RoomID, domain.PeerID, string) ([]byte, error)) *MockAdmissionIssueCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Validate mocks base method.
func (m *MockAdmission) Validate(ctx context.Context, token []byte) (domain.Claims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", ctx, token)
	ret0, _ := ret[0].(domain.Claims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Validate indicates an expected call of Validate.
func (mr *MockAdmissionMockRecorder) Validate(ctx, token any) *MockAdmissionValidateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockAdmission)(nil).Validate), ctx, token)
	return &MockAdmissionValidateCall{Call: call}
}

// MockAdmissionValidateCall wrap *gomock.Call
type MockAdmissionValidateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdmissionValidateCall) Return(arg0 domain.Claims, arg1 error) *MockAdmissionValidateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdmissionValidateCall) Do(f func(context.Context, []byte) (domain.Claims, error)) *MockAdmissionValidateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdmissionValidateCall) DoAndReturn(f func(context.Context, []byte) (domain.Claims, error)) *MockAdmissionValidateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
