// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Sorrowful-free/z-core-frontier-rooms/internal/port/realtime (interfaces: Peer)
//
// Generated by this command:
//
//	mockgen -typed -destination=mock_realtime_peer.go -package=mocks github.com/Sorrowful-free/z-core-frontier-rooms/internal/port/realtime Peer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	domain "github.com/Sorrowful-free/z-core-frontier-rooms/internal/domain"
	events "github.com/Sorrowful-free/z-core-frontier-rooms/internal/domain/events"
	gomock "go.uber.org/mock/gomock"
)

// MockPeer is a mock of Peer interface.
type MockPeer struct {
	ctrl     *gomock.Controller
	recorder *MockPeerMockRecorder
	isgomock struct{}
}

// MockPeerMockRecorder is the mock recorder for MockPeer.
type MockPeerMockRecorder struct {
	mock *MockPeer
}

// NewMockPeer creates a new mock instance.
func NewMockPeer(ctrl *gomock.Controller) *MockPeer {
	mock := &MockPeer{ctrl: ctrl}
	mock.recorder = &MockPeerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPeer) EXPECT() *MockPeerMockRecorder {
	return m.recorder
}

// Deliver mocks base method.
func (m *MockPeer) Deliver(peerEvent events.PeerEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deliver", peerEvent)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deliver indicates an expected call of Deliver.
func (mr *MockPeerMockRecorder) Deliver(peerEvent any) *MockPeerDeliverCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deliver", reflect.TypeOf((*MockPeer)(nil).Deliver), peerEvent)
	return &MockPeerDeliverCall{Call: call}
}

// MockPeerDeliverCall wrap *gomock.Call
type MockPeerDeliverCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPeerDeliverCall) Return(arg0 error) *MockPeerDeliverCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPeerDeliverCall) Do(f func(events.PeerEvent) error) *MockPeerDeliverCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPeerDeliverCall) DoAndReturn(f func(events.PeerEvent) error) *MockPeerDeliverCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetID mocks base method.
func (m *MockPeer) GetID() domain.PeerID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(domain.PeerID)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockPeerMockRecorder) GetID() *MockPeerGetIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockPeer)(nil).GetID))
	return &MockPeerGetIDCall{Call: call}
}

// MockPeerGetIDCall wrap *gomock.Call
type MockPeerGetIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPeerGetIDCall) Return(arg0 domain.PeerID) *MockPeerGetIDCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPeerGetIDCall) Do(f func() domain.PeerID) *MockPeerGetIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPeerGetIDCall) DoAndReturn(f func() domain.PeerID) *MockPeerGetIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetNickName mocks base method.
func (m *MockPeer) GetNickName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNickName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetNickName indicates an expected call of GetNickName.
func (mr *MockPeerMockRecorder) GetNickName() *MockPeerGetNickNameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNickName", reflect.TypeOf((*MockPeer)(nil).GetNickName))
	return &MockPeerGetNickNameCall{Call: call}
}

// MockPeerGetNickNameCall wrap *gomock.Call
type MockPeerGetNickNameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPeerGetNickNameCall) Return(arg0 string) *MockPeerGetNickNameCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPeerGetNickNameCall) Do(f func() string) *MockPeerGetNickNameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPeerGetNickNameCall) DoAndReturn(f func() string) *MockPeerGetNickNameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Ping mocks base method.
func (m *MockPeer) Ping() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping")
	ret0, _ := ret[0].(int64)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockPeerMockRecorder) Ping() *MockPeerPingCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockPeer)(nil).Ping))
	return &MockPeerPingCall{Call: call}
}

// MockPeerPingCall wrap *gomock.Call
type MockPeerPingCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPeerPingCall) Return(arg0 int64) *MockPeerPingCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPeerPingCall) Do(f func() int64) *MockPeerPingCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPeerPingCall) DoAndReturn(f func() int64) *MockPeerPingCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Start mocks base method.
func (m *MockPeer) Start() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockPeerMockRecorder) Start() *MockPeerStartCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockPeer)(nil).Start))
	return &MockPeerStartCall{Call: call}
}

// MockPeerStartCall wrap *gomock.Call
type MockPeerStartCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPeerStartCall) Return(arg0 error) *MockPeerStartCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPeerStartCall) Do(f func() error) *MockPeerStartCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPeerStartCall) DoAndReturn(f func() error) *MockPeerStartCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Stop mocks base method.
func (m *MockPeer) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockPeerMockRecorder) Stop() *MockPeerStopCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockPeer)(nil).Stop))
	return &MockPeerStopCall{Call: call}
}

// MockPeerStopCall wrap *gomock.Call
type MockPeerStopCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPeerStopCall) Return(arg0 error) *MockPeerStopCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPeerStopCall) Do(f func() error) *MockPeerStopCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPeerStopCall) DoAndReturn(f func() error) *MockPeerStopCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
