// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Sorrowful-free/z-core-frontier-rooms/internal/port/realtime (interfaces: PeerFactory)
//
// Generated by this command:
//
//	mockgen -typed -destination=mock_realtime_peer_factory.go -package=mocks github.com/Sorrowful-free/z-core-frontier-rooms/internal/port/realtime PeerFactory
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Sorrowful-free/z-core-frontier-rooms/internal/domain"
	logging "github.com/Sorrowful-free/z-core-frontier-rooms/internal/port/logging"
	realtime "github.com/Sorrowful-free/z-core-frontier-rooms/internal/port/realtime"
	transport "github.com/Sorrowful-free/z-core-frontier-rooms/internal/port/transport"
	gomock "go.uber.org/mock/gomock"
)

// MockPeerFactory is a mock of PeerFactory interface.
type MockPeerFactory struct {
	ctrl     *gomock.Controller
	recorder *MockPeerFactoryMockRecorder
	isgomock struct{}
}

// MockPeerFactoryMockRecorder is the mock recorder for MockPeerFactory.
type MockPeerFactoryMockRecorder struct {
	mock *MockPeerFactory
}

// NewMockPeerFactory creates a new mock instance.
func NewMockPeerFactory(ctrl *gomock.Controller) *MockPeerFactory {
	mock := &MockPeerFactory{ctrl: ctrl}
	mock.recorder = &MockPeerFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPeerFactory) EXPECT() *MockPeerFactoryMockRecorder {
	return m.recorder
}

// CreatePeer mocks base method.
func (m *MockPeerFactory) CreatePeer(ctx context.Context, id domain.PeerID, nickName string, connection transport.Connection, room realtime.Room, logger logging.Logger) (realtime.Peer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePeer", ctx, id, nickName, connection, room, logger)
	ret0, _ := ret[0].(realtime.Peer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePeer indicates an expected call of CreatePeer.
func (mr *MockPeerFactoryMockRecorder) CreatePeer(ctx, id, nickName, connection, room, logger any) *MockPeerFactoryCreatePeerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePeer", reflect.TypeOf((*MockPeerFactory)(nil).CreatePeer), ctx, id, nickName, connection, room, logger)
	return &MockPeerFactoryCreatePeerCall{Call: call}
}

// MockPeerFactoryCreatePeerCall wrap *gomock.Call
type MockPeerFactoryCreatePeerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPeerFactoryCreatePeerCall) Return(arg0 realtime.Peer, arg1 error) *MockPeerFactoryCreatePeerCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPeerFactoryCreatePeerCall) Do(f func(context.Context, domain.PeerID, string, transport.Connection, realtime.Room, logging.Logger) (realtime.Peer, error)) *MockPeerFactoryCreatePeerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPeerFactoryCreatePeerCall) DoAndReturn(f func(context.Context, domain.PeerID, string, transport.Connection, realtime.Room, logging.Logger) (realtime.Peer, error)) *MockPeerFactoryCreatePeerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
