// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Sorrowful-free/z-core-frontier-rooms/internal/port/transport (interfaces: Connection)
//
// Generated by this command:
//
//	mockgen -typed -destination=mock_connection.go -package=mocks github.com/Sorrowful-free/z-core-frontier-rooms/internal/port/transport Connection
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	domain "github.com/Sorrowful-free/z-core-frontier-rooms/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockConnection is a mock of Connection interface.
type MockConnection struct {
	ctrl     *gomock.Controller
	recorder *MockConnectionMockRecorder
	isgomock struct{}
}

// MockConnectionMockRecorder is the mock recorder for MockConnection.
type MockConnectionMockRecorder struct {
	mock *MockConnection
}

// NewMockConnection creates a new mock instance.
func NewMockConnection(ctrl *gomock.Controller) *MockConnection {
	mock := &MockConnection{ctrl: ctrl}
	mock.recorder = &MockConnectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnection) EXPECT() *MockConnectionMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockConnection) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockConnectionMockRecorder) Close() *MockConnectionCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockConnection)(nil).Close))
	return &MockConnectionCloseCall{Call: call}
}

// MockConnectionCloseCall wrap *gomock.Call
type MockConnectionCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConnectionCloseCall) Return(arg0 error) *MockConnectionCloseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConnectionCloseCall) Do(f func() error) *MockConnectionCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConnectionCloseCall) DoAndReturn(f func() error) *MockConnectionCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Ping mocks base method.
func (m *MockConnection) Ping() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping")
	ret0, _ := ret[0].(int64)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockConnectionMockRecorder) Ping() *MockConnectionPingCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockConnection)(nil).Ping))
	return &MockConnectionPingCall{Call: call}
}

// MockConnectionPingCall wrap *gomock.Call
type MockConnectionPingCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConnectionPingCall) Return(arg0 int64) *MockConnectionPingCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConnectionPingCall) Do(f func() int64) *MockConnectionPingCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConnectionPingCall) DoAndReturn(f func() int64) *MockConnectionPingCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Receive mocks base method.
func (m *MockConnection) Receive() (domain.Frame, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Receive")
	ret0, _ := ret[0].(domain.Frame)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Receive indicates an expected call of Receive.
func (mr *MockConnectionMockRecorder) Receive() *MockConnectionReceiveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Receive", reflect.TypeOf((*MockConnection)(nil).Receive))
	return &MockConnectionReceiveCall{Call: call}
}

// MockConnectionReceiveCall wrap *gomock.Call
type MockConnectionReceiveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConnectionReceiveCall) Return(arg0 domain.Frame, arg1 error) *MockConnectionReceiveCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConnectionReceiveCall) Do(f func() (domain.Frame, error)) *MockConnectionReceiveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConnectionReceiveCall) DoAndReturn(f func() (domain.Frame, error)) *MockConnectionReceiveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Send mocks base method.
func (m *MockConnection) Send(frame domain.Frame) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", frame)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockConnectionMockRecorder) Send(frame any) *MockConnectionSendCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockConnection)(nil).Send), frame)
	return &MockConnectionSendCall{Call: call}
}

// MockConnectionSendCall wrap *gomock.Call
type MockConnectionSendCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConnectionSendCall) Return(arg0 error) *MockConnectionSendCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConnectionSendCall) Do(f func(domain.Frame) error) *MockConnectionSendCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConnectionSendCall) DoAndReturn(f func(domain.Frame) error) *MockConnectionSendCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
