// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Sorrowful-free/z-core-frontier-rooms/internal/port/registry (interfaces: RoomRegistry)
//
// Generated by this command:
//
//	mockgen -typed -destination=mock_room_registry.go -package=mocks github.com/Sorrowful-free/z-core-frontier-rooms/internal/port/registry RoomRegistry
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Sorrowful-free/z-core-frontier-rooms/internal/domain"
	realtime "github.com/Sorrowful-free/z-core-frontier-rooms/internal/port/realtime"
	gomock "go.uber.org/mock/gomock"
)

// MockRoomRegistry is a mock of RoomRegistry interface.
type MockRoomRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockRoomRegistryMockRecorder
	isgomock struct{}
}

// MockRoomRegistryMockRecorder is the mock recorder for MockRoomRegistry.
type MockRoomRegistryMockRecorder struct {
	mock *MockRoomRegistry
}

// NewMockRoomRegistry creates a new mock instance.
func NewMockRoomRegistry(ctrl *gomock.Controller) *MockRoomRegistry {
	mock := &MockRoomRegistry{ctrl: ctrl}
	mock.recorder = &MockRoomRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomRegistry) EXPECT() *MockRoomRegistryMockRecorder {
	return m.recorder
}

// CreateRoom mocks base method.
func (m *MockRoomRegistry) CreateRoom(ctx context.Context, id domain.RoomID, capacity int, attributes domain.RoomAttributes) (realtime.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoom", ctx, id, capacity, attributes)
	ret0, _ := ret[0].(realtime.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRoom indicates an expected call of CreateRoom.
func (mr *MockRoomRegistryMockRecorder) CreateRoom(ctx, id, capacity, attributes any) *MockRoomRegistryCreateRoomCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoom", reflect.TypeOf((*MockRoomRegistry)(nil).CreateRoom), ctx, id, capacity, attributes)
	return &MockRoomRegistryCreateRoomCall{Call: call}
}

// MockRoomRegistryCreateRoomCall wrap *gomock.Call
type MockRoomRegistryCreateRoomCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoomRegistryCreateRoomCall) Return(arg0 realtime.Room, arg1 error) *MockRoomRegistryCreateRoomCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoomRegistryCreateRoomCall) Do(f func(context.Context, domain.RoomID, int, domain.RoomAttributes) (realtime.Room, error)) *MockRoomRegistryCreateRoomCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoomRegistryCreateRoomCall) DoAndReturn(f func(context.Context, domain.RoomID, int, domain.RoomAttributes) (realtime.Room, error)) *MockRoomRegistryCreateRoomCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteRoom mocks base method.
func (m *MockRoomRegistry) DeleteRoom(ctx context.Context, id domain.RoomID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRoom", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRoom indicates an expected call of DeleteRoom.
func (mr *MockRoomRegistryMockRecorder) DeleteRoom(ctx, id any) *MockRoomRegistryDeleteRoomCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRoom", reflect.TypeOf((*MockRoomRegistry)(nil).DeleteRoom), ctx, id)
	return &MockRoomRegistryDeleteRoomCall{Call: call}
}

// MockRoomRegistryDeleteRoomCall wrap *gomock.Call
type MockRoomRegistryDeleteRoomCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoomRegistryDeleteRoomCall) Return(arg0 error) *MockRoomRegistryDeleteRoomCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoomRegistryDeleteRoomCall) Do(f func(context.Context, domain.RoomID) error) *MockRoomRegistryDeleteRoomCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoomRegistryDeleteRoomCall) DoAndReturn(f func(context.Context, domain.RoomID) error) *MockRoomRegistryDeleteRoomCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetList mocks base method.
func (m *MockRoomRegistry) GetList(ctx context.Context) ([]realtime.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetList", ctx)
	ret0, _ := ret[0].([]realtime.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetList indicates an expected call of GetList.
func (mr *MockRoomRegistryMockRecorder) GetList(ctx any) *MockRoomRegistryGetListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetList", reflect.TypeOf((*MockRoomRegistry)(nil).GetList), ctx)
	return &MockRoomRegistryGetListCall{Call: call}
}

// MockRoomRegistryGetListCall wrap *gomock.Call
type MockRoomRegistryGetListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoomRegistryGetListCall) Return(arg0 []realtime.Room, arg1 error) *MockRoomRegistryGetListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoomRegistryGetListCall) Do(f func(context.Context) ([]realtime.Room, error)) *MockRoomRegistryGetListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoomRegistryGetListCall) DoAndReturn(f func(context.Context) ([]realtime.Room, error)) *MockRoomRegistryGetListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetRoom mocks base method.
func (m *MockRoomRegistry) GetRoom(ctx context.Context, id domain.RoomID) (realtime.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoom", ctx, id)
	ret0, _ := ret[0].(realtime.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoom indicates an expected call of GetRoom.
func (mr *MockRoomRegistryMockRecorder) GetRoom(ctx, id any) *MockRoomRegistryGetRoomCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoom", reflect.TypeOf((*MockRoomRegistry)(nil).GetRoom), ctx, id)
	return &MockRoomRegistryGetRoomCall{Call: call}
}

// MockRoomRegistryGetRoomCall wrap *gomock.Call
type MockRoomRegistryGetRoomCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoomRegistryGetRoomCall) Return(arg0 realtime.Room, arg1 error) *MockRoomRegistryGetRoomCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoomRegistryGetRoomCall) Do(f func(context.Context, domain.RoomID) (realtime.Room, error)) *MockRoomRegistryGetRoomCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoomRegistryGetRoomCall) DoAndReturn(f func(context.Context, domain.RoomID) (realtime.Room, error)) *MockRoomRegistryGetRoomCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Shutdown mocks base method.
func (m *MockRoomRegistry) Shutdown(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockRoomRegistryMockRecorder) Shutdown(ctx any) *MockRoomRegistryShutdownCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockRoomRegistry)(nil).Shutdown), ctx)
	return &MockRoomRegistryShutdownCall{Call: call}
}

// MockRoomRegistryShutdownCall wrap *gomock.Call
type MockRoomRegistryShutdownCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoomRegistryShutdownCall) Return(arg0 error) *MockRoomRegistryShutdownCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoomRegistryShutdownCall) Do(f func(context.Context) error) *MockRoomRegistryShutdownCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoomRegistryShutdownCall) DoAndReturn(f func(context.Context) error) *MockRoomRegistryShutdownCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
