// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Sorrowful-free/z-core-frontier-rooms/internal/port/identity (interfaces: Allocator)
//
// Generated by this command:
//
//	mockgen -typed -destination=mock_allocator.go -package=mocks github.com/Sorrowful-free/z-core-frontier-rooms/internal/port/identity Allocator
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Sorrowful-free/z-core-frontier-rooms/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAllocator is a mock of Allocator interface.
type MockAllocator struct {
	ctrl     *gomock.Controller
	recorder *MockAllocatorMockRecorder
	isgomock struct{}
}

// MockAllocatorMockRecorder is the mock recorder for MockAllocator.
type MockAllocatorMockRecorder struct {
	mock *MockAllocator
}

// NewMockAllocator creates a new mock instance.
func NewMockAllocator(ctrl *gomock.Controller) *MockAllocator {
	mock := &MockAllocator{ctrl: ctrl}
	mock.recorder = &MockAllocatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAllocator) EXPECT() *MockAllocatorMockRecorder {
	return m.recorder
}

// AllocatePeerID mocks base method.
func (m *MockAllocator) AllocatePeerID(ctx context.Context) (domain.PeerID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllocatePeerID", ctx)
	ret0, _ := ret[0].(domain.PeerID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AllocatePeerID indicates an expected call of AllocatePeerID.
func (mr *MockAllocatorMockRecorder) AllocatePeerID(ctx any) *MockAllocatorAllocatePeerIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllocatePeerID", reflect.TypeOf((*MockAllocator)(nil).AllocatePeerID), ctx)
	return &MockAllocatorAllocatePeerIDCall{Call: call}
}

// MockAllocatorAllocatePeerIDCall wrap *gomock.Call
type MockAllocatorAllocatePeerIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAllocatorAllocatePeerIDCall) Return(arg0 domain.PeerID, arg1 error) *MockAllocatorAllocatePeerIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAllocatorAllocatePeerIDCall) Do(f func(context.Context) (domain.PeerID, error)) *MockAllocatorAllocatePeerIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAllocatorAllocatePeerIDCall) DoAndReturn(f func(context.Context) (domain.PeerID, error)) *MockAllocatorAllocatePeerIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AllocateRoomID mocks base method.
func (m *MockAllocator) AllocateRoomID(ctx context.Context) (domain.RoomID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllocateRoomID", ctx)
	ret0, _ := ret[0].(domain.RoomID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AllocateRoomID indicates an expected call of AllocateRoomID.
func (mr *MockAllocatorMockRecorder) AllocateRoomID(ctx any) *MockAllocatorAllocateRoomIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllocateRoomID", reflect.TypeOf((*MockAllocator)(nil).AllocateRoomID), ctx)
	return &MockAllocatorAllocateRoomIDCall{Call: call}
}

// MockAllocatorAllocateRoomIDCall wrap *gomock.Call
type MockAllocatorAllocateRoomIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAllocatorAllocateRoomIDCall) Return(arg0 domain.RoomID, arg1 error) *MockAllocatorAllocateRoomIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAllocatorAllocateRoomIDCall) Do(f func(context.Context) (domain.RoomID, error)) *MockAllocatorAllocateRoomIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAllocatorAllocateRoomIDCall) DoAndReturn(f func(context.Context) (domain.RoomID, error)) *MockAllocatorAllocateRoomIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
