// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Sorrowful-free/z-core-frontier-rooms/internal/port/realtime (interfaces: Room)
//
// Generated by this command:
//
//	mockgen -typed -destination=mock_realtime_room.go -package=mocks github.com/Sorrowful-free/z-core-frontier-rooms/internal/port/realtime Room
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	domain "github.com/Sorrowful-free/z-core-frontier-rooms/internal/domain"
	events "github.com/Sorrowful-free/z-core-frontier-rooms/internal/domain/events"
	realtime "github.com/Sorrowful-free/z-core-frontier-rooms/internal/port/realtime"
	gomock "go.uber.org/mock/gomock"
)

// MockRoom is a mock of Room interface.
type MockRoom struct {
	ctrl     *gomock.Controller
	recorder *MockRoomMockRecorder
	isgomock struct{}
}

// MockRoomMockRecorder is the mock recorder for MockRoom.
type MockRoomMockRecorder struct {
	mock *MockRoom
}

// NewMockRoom creates a new mock instance.
func NewMockRoom(ctrl *gomock.Controller) *MockRoom {
	mock := &MockRoom{ctrl: ctrl}
	mock.recorder = &MockRoomMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoom) EXPECT() *MockRoomMockRecorder {
	return m.recorder
}

// Deliver mocks base method.
func (m *MockRoom) Deliver(roomEvent events.RoomEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deliver", roomEvent)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deliver indicates an expected call of Deliver.
func (mr *MockRoomMockRecorder) Deliver(roomEvent any) *MockRoomDeliverCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deliver", reflect.TypeOf((*MockRoom)(nil).Deliver), roomEvent)
	return &MockRoomDeliverCall{Call: call}
}

// MockRoomDeliverCall wrap *gomock.Call
type MockRoomDeliverCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoomDeliverCall) Return(arg0 error) *MockRoomDeliverCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoomDeliverCall) Do(f func(events.RoomEvent) error) *MockRoomDeliverCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoomDeliverCall) DoAndReturn(f func(events.RoomEvent) error) *MockRoomDeliverCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetID mocks base method.
func (m *MockRoom) GetID() domain.RoomID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(domain.RoomID)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockRoomMockRecorder) GetID() *MockRoomGetIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockRoom)(nil).GetID))
	return &MockRoomGetIDCall{Call: call}
}

// MockRoomGetIDCall wrap *gomock.Call
type MockRoomGetIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoomGetIDCall) Return(arg0 domain.RoomID) *MockRoomGetIDCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoomGetIDCall) Do(f func() domain.RoomID) *MockRoomGetIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoomGetIDCall) DoAndReturn(f func() domain.RoomID) *MockRoomGetIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetPeer mocks base method.
func (m *MockRoom) GetPeer(peerID domain.PeerID) (realtime.Peer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPeer", peerID)
	ret0, _ := ret[0].(realtime.Peer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPeer indicates an expected call of GetPeer.
func (mr *MockRoomMockRecorder) GetPeer(peerID any) *MockRoomGetPeerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPeer", reflect.TypeOf((*MockRoom)(nil).GetPeer), peerID)
	return &MockRoomGetPeerCall{Call: call}
}

// MockRoomGetPeerCall wrap *gomock.Call
type MockRoomGetPeerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoomGetPeerCall) Return(arg0 realtime.Peer, arg1 error) *MockRoomGetPeerCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoomGetPeerCall) Do(f func(domain.PeerID) (realtime.Peer, error)) *MockRoomGetPeerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoomGetPeerCall) DoAndReturn(f func(domain.PeerID) (realtime.Peer, error)) *MockRoomGetPeerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetPeers mocks base method.
func (m *MockRoom) GetPeers() []realtime.Peer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPeers")
	ret0, _ := ret[0].([]realtime.Peer)
	return ret0
}

// GetPeers indicates an expected call of GetPeers.
func (mr *MockRoomMockRecorder) GetPeers() *MockRoomGetPeersCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPeers", reflect.TypeOf((*MockRoom)(nil).GetPeers))
	return &MockRoomGetPeersCall{Call: call}
}

// MockRoomGetPeersCall wrap *gomock.Call
type MockRoomGetPeersCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoomGetPeersCall) Return(arg0 []realtime.Peer) *MockRoomGetPeersCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoomGetPeersCall) Do(f func() []realtime.Peer) *MockRoomGetPeersCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoomGetPeersCall) DoAndReturn(f func() []realtime.Peer) *MockRoomGetPeersCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// HasPeer mocks base method.
func (m *MockRoom) HasPeer(peerID domain.PeerID) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasPeer", peerID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasPeer indicates an expected call of HasPeer.
func (mr *MockRoomMockRecorder) HasPeer(peerID any) *MockRoomHasPeerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasPeer", reflect.TypeOf((*MockRoom)(nil).HasPeer), peerID)
	return &MockRoomHasPeerCall{Call: call}
}

// MockRoomHasPeerCall wrap *gomock.Call
type MockRoomHasPeerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoomHasPeerCall) Return(arg0 bool) *MockRoomHasPeerCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoomHasPeerCall) Do(f func(domain.PeerID) bool) *MockRoomHasPeerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoomHasPeerCall) DoAndReturn(f func(domain.PeerID) bool) *MockRoomHasPeerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Join mocks base method.
func (m *MockRoom) Join(peer realtime.Peer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Join", peer)
	ret0, _ := ret[0].(error)
	return ret0
}

// Join indicates an expected call of Join.
func (mr *MockRoomMockRecorder) Join(peer any) *MockRoomJoinCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Join", reflect.TypeOf((*MockRoom)(nil).Join), peer)
	return &MockRoomJoinCall{Call: call}
}

// MockRoomJoinCall wrap *gomock.Call
type MockRoomJoinCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoomJoinCall) Return(arg0 error) *MockRoomJoinCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoomJoinCall) Do(f func(realtime.Peer) error) *MockRoomJoinCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoomJoinCall) DoAndReturn(f func(realtime.Peer) error) *MockRoomJoinCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Leave mocks base method.
func (m *MockRoom) Leave(peer realtime.Peer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Leave", peer)
	ret0, _ := ret[0].(error)
	return ret0
}

// Leave indicates an expected call of Leave.
func (mr *MockRoomMockRecorder) Leave(peer any) *MockRoomLeaveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Leave", reflect.TypeOf((*MockRoom)(nil).Leave), peer)
	return &MockRoomLeaveCall{Call: call}
}

// MockRoomLeaveCall wrap *gomock.Call
type MockRoomLeaveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoomLeaveCall) Return(arg0 error) *MockRoomLeaveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoomLeaveCall) Do(f func(realtime.Peer) error) *MockRoomLeaveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoomLeaveCall) DoAndReturn(f func(realtime.Peer) error) *MockRoomLeaveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Replace mocks base method.
func (m *MockRoom) Replace(peer realtime.Peer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Replace", peer)
	ret0, _ := ret[0].(error)
	return ret0
}

// Replace indicates an expected call of Replace.
func (mr *MockRoomMockRecorder) Replace(peer any) *MockRoomReplaceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Replace", reflect.TypeOf((*MockRoom)(nil).Replace), peer)
	return &MockRoomReplaceCall{Call: call}
}

// MockRoomReplaceCall wrap *gomock.Call
type MockRoomReplaceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoomReplaceCall) Return(arg0 error) *MockRoomReplaceCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoomReplaceCall) Do(f func(realtime.Peer) error) *MockRoomReplaceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoomReplaceCall) DoAndReturn(f func(realtime.Peer) error) *MockRoomReplaceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Send mocks base method.
func (m *MockRoom) Send(peerEvent events.PeerEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", peerEvent)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockRoomMockRecorder) Send(peerEvent any) *MockRoomSendCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockRoom)(nil).Send), peerEvent)
	return &MockRoomSendCall{Call: call}
}

// MockRoomSendCall wrap *gomock.Call
type MockRoomSendCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoomSendCall) Return(arg0 error) *MockRoomSendCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoomSendCall) Do(f func(events.PeerEvent) error) *MockRoomSendCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoomSendCall) DoAndReturn(f func(events.PeerEvent) error) *MockRoomSendCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Start mocks base method.
func (m *MockRoom) Start() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockRoomMockRecorder) Start() *MockRoomStartCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockRoom)(nil).Start))
	return &MockRoomStartCall{Call: call}
}

// MockRoomStartCall wrap *gomock.Call
type MockRoomStartCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoomStartCall) Return(arg0 error) *MockRoomStartCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoomStartCall) Do(f func() error) *MockRoomStartCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoomStartCall) DoAndReturn(f func() error) *MockRoomStartCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Stop mocks base method.
func (m *MockRoom) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockRoomMockRecorder) Stop() *MockRoomStopCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockRoom)(nil).Stop))
	return &MockRoomStopCall{Call: call}
}

// MockRoomStopCall wrap *gomock.Call
type MockRoomStopCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoomStopCall) Return(arg0 error) *MockRoomStopCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoomStopCall) Do(f func() error) *MockRoomStopCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoomStopCall) DoAndReturn(f func() error) *MockRoomStopCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
