// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Sorrowful-free/z-core-frontier-rooms/internal/port/httplimits (interfaces: Limits)
//
// Generated by this command:
//
//	mockgen -typed -destination=mock_httplimits.go -package=mocks github.com/Sorrowful-free/z-core-frontier-rooms/internal/port/httplimits Limits
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLimits is a mock of Limits interface.
type MockLimits struct {
	ctrl     *gomock.Controller
	recorder *MockLimitsMockRecorder
	isgomock struct{}
}

// MockLimitsMockRecorder is the mock recorder for MockLimits.
type MockLimitsMockRecorder struct {
	mock *MockLimits
}

// NewMockLimits creates a new mock instance.
func NewMockLimits(ctrl *gomock.Controller) *MockLimits {
	mock := &MockLimits{ctrl: ctrl}
	mock.recorder = &MockLimitsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLimits) EXPECT() *MockLimitsMockRecorder {
	return m.recorder
}

// AllowCreateRoom mocks base method.
func (m *MockLimits) AllowCreateRoom(currentRoomCount int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllowCreateRoom", currentRoomCount)
	ret0, _ := ret[0].(error)
	return ret0
}

// AllowCreateRoom indicates an expected call of AllowCreateRoom.
func (mr *MockLimitsMockRecorder) AllowCreateRoom(currentRoomCount any) *MockLimitsAllowCreateRoomCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllowCreateRoom", reflect.TypeOf((*MockLimits)(nil).AllowCreateRoom), currentRoomCount)
	return &MockLimitsAllowCreateRoomCall{Call: call}
}

// MockLimitsAllowCreateRoomCall wrap *gomock.Call
type MockLimitsAllowCreateRoomCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLimitsAllowCreateRoomCall) Return(arg0 error) *MockLimitsAllowCreateRoomCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLimitsAllowCreateRoomCall) Do(f func(int) error) *MockLimitsAllowCreateRoomCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLimitsAllowCreateRoomCall) DoAndReturn(f func(int) error) *MockLimitsAllowCreateRoomCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AllowHTTPCreate mocks base method.
func (m *MockLimits) AllowHTTPCreate(clientIP string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllowHTTPCreate", clientIP)
	ret0, _ := ret[0].(bool)
	return ret0
}

// AllowHTTPCreate indicates an expected call of AllowHTTPCreate.
func (mr *MockLimitsMockRecorder) AllowHTTPCreate(clientIP any) *MockLimitsAllowHTTPCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllowHTTPCreate", reflect.TypeOf((*MockLimits)(nil).AllowHTTPCreate), clientIP)
	return &MockLimitsAllowHTTPCreateCall{Call: call}
}

// MockLimitsAllowHTTPCreateCall wrap *gomock.Call
type MockLimitsAllowHTTPCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLimitsAllowHTTPCreateCall) Return(arg0 bool) *MockLimitsAllowHTTPCreateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLimitsAllowHTTPCreateCall) Do(f func(string) bool) *MockLimitsAllowHTTPCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLimitsAllowHTTPCreateCall) DoAndReturn(f func(string) bool) *MockLimitsAllowHTTPCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AllowHTTPIssueTicket mocks base method.
func (m *MockLimits) AllowHTTPIssueTicket(clientIP string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllowHTTPIssueTicket", clientIP)
	ret0, _ := ret[0].(bool)
	return ret0
}

// AllowHTTPIssueTicket indicates an expected call of AllowHTTPIssueTicket.
func (mr *MockLimitsMockRecorder) AllowHTTPIssueTicket(clientIP any) *MockLimitsAllowHTTPIssueTicketCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllowHTTPIssueTicket", reflect.TypeOf((*MockLimits)(nil).AllowHTTPIssueTicket), clientIP)
	return &MockLimitsAllowHTTPIssueTicketCall{Call: call}
}

// MockLimitsAllowHTTPIssueTicketCall wrap *gomock.Call
type MockLimitsAllowHTTPIssueTicketCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLimitsAllowHTTPIssueTicketCall) Return(arg0 bool) *MockLimitsAllowHTTPIssueTicketCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLimitsAllowHTTPIssueTicketCall) Do(f func(string) bool) *MockLimitsAllowHTTPIssueTicketCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLimitsAllowHTTPIssueTicketCall) DoAndReturn(f func(string) bool) *MockLimitsAllowHTTPIssueTicketCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
